library(arfima)
dax <- read.table(file="C:\\pruebas_r\\DAX_ret.dat", header=FALSE)
dax <- ts(dax, start = c(1981, 1), frequency = 365)
plot(dax)
acf(dax,lag.max=30)
pacf(dax,lag.max=30)
acf(dax^2,lag.max=30)
pacf(dax^2,lag.max=30)
acf(abs(dax),lag.max=30)
pacf(abs(dax),lag.max=30)
spectrum(abs(dax), method="ar")
spectrum(abs(dax))
spectrum(abs(dax), kernel("fejer",50,r=6))
fit<-arfima(abs(dax))
res_fit <-residuals(fit)
acf(res_fit$Mode1,lag.max = 100)
pacf(res_fit$Mode1,lag.max = 100)
spectrum(res_fit$Mode1, method="ar")
spectrum(res_fit$Mode1)
spectrum(res_fit$Mode1, kernel("fejer",50,r=6))
