el <- read.table(file="C:\\pruebas_r\\elec.dat", header=FALSE)
elec <- ts(el, start = c(1948, 1), frequency = 12)
kk=nrow(elec)/12
elm <- matrix(data=elec,nrow=kk,ncol=12,byrow=TRUE)
ela=rowSums(elm)
eleca <- ts(ela, start = 1948, frequency = 1)
plot(eleca)
plot(log(eleca))
acf(log(eleca),lag.max=12)
pacf(log(eleca),lag.max=12)
m1=arima(log(eleca),order=c(1,0,0),include.mean = TRUE)

acf(diff(log(eleca),1),lag.max=12)
pacf(diff(log(eleca),1),lag.max=12)
plot(diff(log(eleca),1))
d1<-rep(1,59)
m1=arima(log(eleca),order=c(1,1,0),xreg = d1)
res_m1=residuals(m1)
plot(res_m1)
acf(res_m1,lag.max = 12)
pacf(res_m1,lag.max = 12)
tsdiag(m1)
Box.test(res_m1,lag=12,type="Ljung-Box")

m2=arima(log(eleca),order=c(2,1,0),xreg = d1)
res_m2=residuals(m2)
acf(res_m2,lag.max = 12)
pacf(res_m2,lag.max = 12)
plot(res_m2)
tsdiag(m2)
Box.test(res_m2,lag=12,type="Ljung-Box")

m3=arima(log(eleca),order=c(1,1,1),xreg = d1)
res_m3=residuals(m3)
acf(res_m3,lag.max = 12)
pacf(res_m3,lag.max = 12)
plot(res_m3)
tsdiag(m3)
Box.test(res_m3,lag=12,type="Ljung-Box")

