library(arfima)
sim <- arfima.sim(1000, model = list(phi =c(0.5,-0.8),dfrac = .4))
acf(sim,lag.max = 100)
spectrum(sim, method="ar")
spectrum(sim)
spectrum(sim, kernel("fejer",50,r=6))
fit<-arfima(sim)
res_fit <-residuals(fit)
acf(res_fit$Mode1,lag.max = 100)
spectrum(res_fit$Mode1, method="ar")
spectrum(res_fit$Mode1)
spectrum(res_fit$Mode1, kernel("fejer",50,r=6))
fit2<-arfima(sim,order=c(2,0,0))
res_fit2 <-residuals(fit2)
acf(res_fit2$Mode1,lag.max = 100)
spectrum(res_fit2$Mode1, method="ar")
spectrum(res_fit2$Mode1)
spectrum(res_fit2$Mode1, kernel("fejer",50,r=6))
