library(arfima)
sim <- arfima.sim(1000, model = list(dfrac = .4))
acf(sim,lag.max = 100)
fit<-arfima(sim)
res_fit <-residuals(fit)
spectrum(sim, method="ar")
spectrum(sim)
spectrum(sim, kernel("fejer",50,r=6))
acf(res_fit$Mode1,lag.max = 100)
